name: backend
description: "Dart backend for APIs"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.6
  logging: ^1.2.0
  http: ^1.2.2
  html: ^0.15.4
  intl: ^0.19.0
  shelf_static: ^1.1.3 
  mailer: ^6.1.0

assets:
    - assets/images/logo_central.png
    - assets/images/logo_pacific.png
